# Generated by Django 5.1.2 on 2024-11-04 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_creada', models.DateTimeField(auto_now_add=True)),
                ('categoria_actualizada', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HistorialEstados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historial_creado', models.DateTimeField(auto_now_add=True)),
                ('historial_actualizado', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('preparación', 'Preparación'), ('enviado', 'Enviado'), ('entregado', 'Entregado')], default='preparación', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Mesas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesa_creada', models.DateTimeField(auto_now_add=True)),
                ('mesa_actualizada', models.DateTimeField(auto_now=True)),
                ('numero_mesa', models.IntegerField()),
                ('capacidad_mesa', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MesasEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_mesa_creado', models.DateTimeField(auto_now_add=True)),
                ('estado_mesa_actualizado', models.DateTimeField(auto_now=True)),
                ('nombre_estado', models.CharField(choices=[('disponible', 'Disponible'), ('reservada', 'Reservada'), ('Disponible', 'disponible'), ('Reservada', 'reservada')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MetodoDePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pago_creado', models.DateTimeField(auto_now_add=True)),
                ('metodo_pago_actualizado', models.DateTimeField(auto_now=True)),
                ('tipo_pago', models.CharField(max_length=50)),
                ('fecha_compra', models.DateField()),
                ('total_compra', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('factura_actualizada', models.DateTimeField(auto_now=True)),
                ('total_factura', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cliente_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mesa_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mesas')),
                ('metodo_pago_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.metododepago')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_creado', models.DateTimeField(auto_now_add=True)),
                ('menu_actualizado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disponibilidad', models.BooleanField(default=True)),
                ('categoria_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.categoriamenu')),
            ],
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario_creado', models.DateTimeField(auto_now_add=True)),
                ('comentario_actualizado', models.DateTimeField(auto_now=True)),
                ('comentario', models.TextField()),
                ('calificacion', models.IntegerField()),
                ('cliente_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('menu_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.menu')),
            ],
        ),
        migrations.AddField(
            model_name='mesas',
            name='estado_mesa_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mesasestado'),
        ),
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificacion_creada', models.DateTimeField(auto_now_add=True)),
                ('notificacion_actualizada', models.DateTimeField(auto_now=True)),
                ('mensaje', models.TextField()),
                ('leido', models.BooleanField()),
                ('cliente_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido_creado', models.DateTimeField(auto_now_add=True)),
                ('pedido_actualizado', models.DateTimeField(auto_now=True)),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('cliente_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('estado_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.historialestados')),
            ],
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promocion_creado', models.DateTimeField(auto_now_add=True)),
                ('promocion_actualizado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('descuento', models.IntegerField()),
                ('fecha_vencimiento', models.DateTimeField()),
                ('menu_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.menu')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle_pedido_creado', models.DateTimeField(auto_now_add=True)),
                ('detalle_pedido_actualizado', models.DateTimeField(auto_now=True)),
                ('cantidad', models.IntegerField()),
                ('subtotal', models.IntegerField()),
                ('iva', models.IntegerField()),
                ('total', models.IntegerField()),
                ('factura_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.factura')),
                ('menu_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.menu')),
                ('pedido_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pedido')),
                ('promocion_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.promocion')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserva_creada', models.DateTimeField(auto_now_add=True)),
                ('reserva_actualizada', models.DateTimeField(auto_now=True)),
                ('fecha_reserva', models.DateTimeField()),
                ('cliente_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mesa_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mesas')),
                ('metodo_pago_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.metododepago')),
            ],
        ),
    ]
